import "@/styles/globals.css";
import type { Metadata } from "next";
import AuthProvider from "../components/provider";
import {StoreProvider} from "@/components/storeProvider";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Heyo Chat",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <StoreProvider>
      <AuthProvider>
        <html lang="en">
          {/* @ts-ignore */}
          <body className="max-w-[1920px] mx-auto">{children}</body>
          <Toaster />
        </html>
      </AuthProvider>
    </StoreProvider>
  );
}
