import "@/styles/globals.css";
import type { Metadata } from "next";
import Provider from "../components/provider";
import { getServerSession } from "next-auth";
import { redirect } from "next/navigation";
import { authOptions } from "./api/auth/[...nextauth]/route";

export const metadata: Metadata = {
  title: "Heyo Chat",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Provider>
      <html lang="en">
        {/* @ts-ignore */}
        <body className="max-w-[1920px] mx-auto">{children}</body>
      </html>
    </Provider>
  );
}
