import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Heyo Chat",
  description: "Generated by create next app",
};

export default function ChatLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <section className="m-auto h-screen w-full bg-background">
      <div className="h-screen m-auto">{children}</div>
    </section>
  );
}
