"use client"

import type { Metadata } from "next";
import { ZimContext } from "@/store/zimContext";
import { useState } from "react";
import ZIM from "zego-zim-web";

// export const metadata: Metadata = {
//   title: "Heyo Chat",
//   description: "Generated by create next app",
// };

export default function ChatLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  const [zim, setZim] = useState<ZIM | null>(null);

  return (
    <ZimContext.Provider value={{zim, setZim}}>
      <section className="m-auto h-screen overflow-hidden w-full bg-background">
        <div className="h-screen m-auto">{children}</div>
      </section>
    </ZimContext.Provider>
  );
}
